### ISSUE TITLE
Use https link for http://opencontent.org/openpub/

### ISSUE THREAD

**Issue by imirkin** [KhronosGroup/OpenGL-Refpages#114]
Just needs a global `find . -type f -print0 | xargs -0 sed -i s,http://opencontent,https://opencontent,g` on the repository. Happy to do it, but probably easier for the person approving the change in the first place to do it themselves.

**Comment by oddhack** [comment]
opencontent.org appears to be completely down, whether HTTP or HTTPS, so that doesn't help much. I don't know if there's a canonical source for this license, at this point, though copies can be found elsewhere. We're unable to change it since the licensing entity no longer exists in that form. 3Dlabs underwent a series of name changes, aquisitions, and spinoffs, and the current IP rights probably lie with some combination of Creative and Intel. It's definitely not worth the months or years it would take to try and identify the owner and get their permission to change to a different license.

**Comment by imirkin** [comment]
Are you sure? Seems to load fine for me... https://opencontent.org/openpub/

**Comment by oddhack** [comment]
Must have been a transient outage.

**Comment by iwikal** [comment]
I am now greeted by a message saying the "Account has been suspended". That doesn't sound very transient... hopefully they'll sort out a new hosting provider.
