### ISSUE TITLE
Allow for deeplinking directly to commands

### ISSUE THREAD

**Issue by bjartwolf** [KhronosGroup/OpenGL-Refpages#160]
Currently it is not possible to link to commands directly. 

I can link to https://registry.khronos.org/OpenGL-Refpages/es3.0/
or deeplink to https://registry.khronos.org/OpenGL-Refpages/es3.0/html/glBindRenderbuffer.xhtml, but in the last case I miss the menu, as I just open the page and I loose the frame and I can not navigate.

The use case is looking up commands from an editor, in my case neovim, in the browser to read documentation, and even though this works now, I can't continue navigating as the menu is gone when I link directly to a subpage such as https://registry.khronos.org/OpenGL-Refpages/es3.0/html/glBeginQuery.xhtml

I understand getting rid of frames is a larger issue.

I was thinking I could add something allowing for some javascript in the menu reading a query parameter with the command and if it matches one of the elements in the menu it would open it. This should be pretty hard to use for anything malicious as the menu would be a whitelist... Let me know if such a PR is something that could be approved and I would write it.

**Comment by oddhack** [comment]
DYM something like 'https:...OpenGL-Refpages/es3.0?page=glBindRenderbuffer ? That's probably tractable since the framing is essentially static HTML, though the menu is generated and checked in so would have to be careful it does not overwrite any added scripts. I won't promise we'd take it but if it was non-intrusive on existing use I don't see why not.

TBH we are unlikely to do more than very minor maintenance on the refpages ourselves. They're marked up in a very ancient Docbook(*) format and toolchain and way too much work to contemplate converting to something more modern - otherwise I'd probably put it in an Antora / asciidoc static HTML generator format like docs.vulkan.org.

(*) Which is at least better than the nroff format they started with based on the SGI Irix pages :-)

**Comment by bjartwolf** [comment]
Yes, that was my thinking. If possible something not very intrusive, that if it breaks it breaks silently by just failing to open the subpage and something that whitelists its input by doing stuff only if it finds that element in the dom. Something pretty much based on picking up the query parameter, finding the element that links to it by querying the DOM and if it finds it, open that link. If not, nothing happens, if it crashes, nothing should happen.

<img width="846" alt="image" src="https://github.com/user-attachments/assets/fe3a259e-a843-4a9d-9cb8-c555e90f73e9">

I don't need any guarantees on the PR, but I just wanted to see you were not opposed to the idea, the project is alive before I went ahead and installed PHP to work on it locally :)

**Comment by bjartwolf** [comment]
Maybe there are some smoothers ways to do this, but it seemed to me one has to pick up the query from the top and inject it in all the frames until the desired frames.

**Comment by bjartwolf** [comment]
The version in the PoC https://github.com/KhronosGroup/OpenGL-Refpages/pull/161 could be fairly easily implemented in the python generator, if this is something you would consider accepting let me know and I could make a proper PR. I think it is easier to follow the idea with looking at the generated code than reading the code generator...

**Comment by bjartwolf** [comment]
I think the version with javascript to inject query params calls for unnescessary pageloads, and the one with php sounds scary, as it must be heavy sanitized when running php code with user input, and I don't know php that well.
