### ISSUE TITLE
Add the website build machinery

### ISSUE THREAD

**Issue by NicolBolas** [KhronosGroup/OpenGL-Refpages#9]
The old SVN repo for these pages had the build tools included. The current GitHub one does not.

**Comment by oddhack** [comment]
There probably should be a Makefile at the top level which descends into each gl* es* directory and does a make there. What do you think is missing? There isn't any "website build machinery" because the pages on khronos.org are pulled directly out of a clone of the git repo, although we're only about halfway done setting up redirects from the old sdk/docs/ URLs

**Comment by oddhack** [comment]
I added a Makefile and updated the toplevel README.adoc with some build information.
